# Generated by Django 3.0.8 on 2020-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='forfeited',
            new_name='resigned',
        ),
    ]
