# Generated by Django 3.0.7 on 2020-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='outcome',
            field=models.IntegerField(default=-1),
        ),
    ]
