# Generated by Django 3.0.7 on 2020-07-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_boardmodel_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statemodel',
            old_name='game',
            new_name='game_id',
        ),
    ]
