# Generated by Django 3.0.8 on 2020-08-06 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_boardmodel_rematch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='changemodel',
            managers=[
                ('changes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='changemodel',
            name='action',
        ),
        migrations.AddField(
            model_name='changemodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.StateModel'),
        ),
    ]
