# Generated by Django 3.0.8 on 2020-08-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200808_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='games.BoardModel')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root', to='games.BoardModel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.StateModel')),
            ],
        ),
    ]
