# Generated by Django 3.0.8 on 2020-08-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200806_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemodel',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.StateModel'),
            preserve_default=False,
        ),
    ]
