# Generated by Django 3.0.8 on 2020-08-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_forkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='root_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root', to='games.BoardModel'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='root_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root', to='games.StateModel'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='rematch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_board', to='games.BoardModel'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='games.StateModel'),
        ),
        migrations.DeleteModel(
            name='ForkModel',
        ),
    ]
