# Generated by Django 3.0.7 on 2020-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200623_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
