# Generated by Django 3.0.8 on 2020-08-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200827_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='rematch',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='rematch_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch', to='games.BoardModel'),
        ),
    ]
