# Generated by Django 3.0.7 on 2020-06-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_board_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
