# Generated by Django 3.0.8 on 2020-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_statemodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecemodel',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
