# Generated by Django 3.0.8 on 2020-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200801_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatemodel',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
