# Generated by Django 3.0.7 on 2020-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_player_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-started']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['board', '-time']},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['state']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['board', 'order']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['board']},
        ),
        migrations.AddField(
            model_name='state',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
