# Generated by Django 3.0.7 on 2020-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200626_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='started',
            new_name='time',
        ),
        migrations.AddField(
            model_name='player',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
