# Generated by Django 3.0.8 on 2020-08-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_playerstatemodel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='forfeited',
            field=models.BooleanField(default=False),
        ),
    ]
