# Generated by Django 3.0.7 on 2020-06-27 12:04

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200627_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
