# Generated by Django 3.0.7 on 2020-06-27 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200627_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
