# Generated by Django 3.0.7 on 2020-06-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200627_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='time',
        ),
    ]
