# Generated by Django 3.0.7 on 2020-06-27 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_player_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
