# Generated by Django 3.0.7 on 2020-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_player_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='game',
        ),
        migrations.RemoveField(
            model_name='state',
            name='number',
        ),
        migrations.AlterField(
            model_name='state',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
