# Generated by Django 3.0.7 on 2020-06-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20200630_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='board',
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.State'),
        ),
    ]
