# Generated by Django 3.0.7 on 2020-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20200630_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='game_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='game_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
