# Generated by Django 3.0.7 on 2020-07-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20200701_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='game_id',
        ),
        migrations.AddField(
            model_name='state',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.State'),
        ),
    ]
