# Generated by Django 3.0.7 on 2020-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20200701_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.RemoveField(
            model_name='piece',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='state',
            name='board',
        ),
        migrations.AddField(
            model_name='piece',
            name='owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='game_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
