# Generated by Django 3.0.7 on 2020-07-01 08:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200701_0805'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='board',
            managers=[
                ('boards', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='ply',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='turn',
            field=models.IntegerField(),
        ),
    ]
