# Generated by Django 3.0.7 on 2020-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20200701_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='type',
            new_name='type_id',
        ),
    ]
